TARGETS=energy.pdf angular_circular.pdf friction.pdf Impulse.pdf momentum.pdf NewtonIII.pdf NewtonI.pdf zero_momentum_frame.pdf

include ../../../../../makefile/latex-to-pdf.mk

angular_circular.dvi: figures/circular.eps figures/centripetal.eps figures/centripetal_derive.eps

friction.dvi: figures/friction_defs.eps figures/slope.eps

Impulse.tex: figures/Impulse1.eps figures/Momentum1.eps figures/Momentum2.eps

momentum.tex: figures/collision.eps figures/inelastic.eps figures/elastic.eps figures/wall.eps

NewtonIII.tex: figures/NewtonIII1.eps figures/NewtonIII2.eps figures/NewtonIII3.eps

NewtonI.tex: figures/FreeBody1.eps figures/FreeBody2.eps

zero_momentum_frame.tex: figures/ZMF1.eps figures/ZMF2.eps figures/ZMF1a.eps figures/ZMF2a.eps figures/ZMF3.eps figures/ZMF4.eps
